Added guide for token gated rooms on Solana
Huddle01/docs pull request #38
Opened 2024-03-05 20:09 UTC by vrajdesai78

2024-03-06 10:10 UTC, mizanxali commented on pages/guides/solana-token-gated.mdx
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
rm this eslint-disable

2024-03-06 10:11 UTC, mizanxali commented on pages/guides/solana-token-gated.mdx
> +                <title>Solan Token Gated Example</title>
solana

2024-03-06 10:14 UTC, mizanxali commented on pages/guides/solana-token-gated.mdx
> +
just add the main component declaration line

```
export default function Home() {
// rest of the code
}
```

2024-03-06 10:14 UTC, mizanxali requested changes
added comments

2024-03-06 10:25 UTC, vrajdesai78 commented
> added comments

Pushed required changes

2024-03-07 05:15 UTC, mizanxali approved these changes

2024-03-07 05:15 UTC, merged